<?php
define('VERSAO', '1.1.0');

define('QTD_HORAS_ALTERACAO_PRONTUARIO', 96);

define('ADM_SISID', 72);
define('ADM_PERFIL_GERAL', 437);
define('ADM_PERFIL_LOCAL', 438);
define('ADM_PERFIL_REPRESENTANTE', 439);
define('ADM_PERFIL_PROFISSIONAL_SAUDE', 440);
define('ADM_PERFIL_RECEPCIONISTA', 441);
define('ADM_PERFIL_CORRETOR_AGENDA', 450);

define('ABA_MEDICO', 57273);

define('PERCENTUAL_GLOBAL_REPASSE_MEDICO', 80);

//Constantes de categoria de mensagem do clubvida
define('CATEGORIA_MENSAGEM_AGENDAMENTO_CONSULTA', 1);

if(getenv("APP_ENV") == 'prod')
{
    define('TIPO_CONSULTA_REMOTA', 31);
    define('TIPO_CONSULTA_RETORNO_REMOTO', 32);
}else{
    define('TIPO_CONSULTA_REMOTA', 6);
    define('TIPO_CONSULTA_RETORNO_REMOTO', 7);
}

//CONSTANTES DO CLUBVIDA CARD
define('TIPO_DOCUMENTO_FLUXO_ADERENCIA_CARTAO_BENEFICIOS', 7401);
define('ESTADO_DOCUMENTO_ADERENCIA_CARTAO_BENEFICIOS_AGUARDANDO_PAGAMENTO', 740101);
define('ESTADO_DOCUMENTO_ADERENCIA_CARTAO_BENEFICIOS_ATIVO', 740101);
define('ESTADO_DOCUMENTO_ADERENCIA_CARTAO_BENEFICIOS_CANCELADO', 740101);
define('ESTADO_DOCUMENTO_ADERENCIA_CARTAO_BENEFICIOS_INATIVO_FALTA_PAGAMENTO', 740101);