                <br />
            </div>
        </div>
        <div class="footer">
            <div class="text-left col-sm-6 col-xs-8">
                <div class="padding">
                    &copy; <?= date('Y') ?> Mesotec. <br/>Todos os Direitos Reservados.
                </div>
            </div>
            <div class="text-right col-sm-6 col-xs-4">
                <div class="padding">
                    <img src="/imagens/logo_mesotec_branca.png" alt=" " />
                </div>
            </div>
    	</div>
    </body>
</html>
