    <div class="tab-pane fade " id="kt_tab_contratacao" role="tabpanel">
    <div class="row">
            <div class="col-md-6">
                <?php
                require('dados_edital.inc');
                ?>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title collapsed" data-toggle="collapse" data-target="#contatacao_documentacao">
                            <b> <i class="bi bi-file-earmark-check"></i> Documentação </b>
                        </div>
                    </div>
                    <div id="contatacao_documentacao" class="collapse">
                        <div class="card-body">
                            Em breve.
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <div class="card-title collapsed" data-toggle="collapse" data-target="#equipe_base">
                            <b> <i class="bi bi-person-check"></i> Equipe Base Inicial</b>
                        </div>
                    </div>
                    <div id="equipe_base" class="collapse">
                        <div class="card-body">
                            Em breve.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>