<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label><b>Número do Contrato</b></label>
            <br />
            0000000/0000
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label><b>Processo Adminsitrativo</b></label>
            <br />
            SEI 00000000000/00000
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label><b>Vencimento do contrato</b></label>
            <br />
            00/00/0000
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label><b>Edital</b></label>
            <br />
            <?php echo $dados['portal'] ?>
            <br>
            <?php echo $dados['edital'] ?>
        </div>
    </div>
</div>
<div class="row">
<div class="col-md-6">
        <div class="form-group">
            <label><b>Responsável Interno</b></label>
            <br />
            Fulano de tal
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label><b>Valor total</b></label>
            <br />
            <b class="font-blue-sharp">
                R$ 0.000.000,00
            </b>
        </div>
    </div>
</div>