    <div class="tab-pane fade" id="kt_tab_gestao_contrato" role="tabpanel">
    <div class="row">
            <div class="col-md-6">
                <?php
                require('dados_contrato.inc');
                ?>
            </div>
            <div class="col-md-6">
            <div class="card">
                    <div class="card-header">
                        <div class="card-title collapsed" data-toggle="collapse" data-target="#contrato_documentacao">
                            <b> <i class="bi bi-file-earmark-check"></i> Documentação </b>
                        </div>
                    </div>
                    <div id="contrato_documentacao" class="collapse">
                        <div class="card-body">
                            Em breve.
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <div class="card-title collapsed" data-toggle="collapse" data-target="#acompanhamento_problemas">
                            <b> <i class="bi bi-sun"></i> Acompanhamento (problemas e soluções)</b>
                        </div>
                    </div>
                    <div id="acompanhamento_problemas" class="collapse">
                        <div class="card-body">
                            Em breve.
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <div class="card-title collapsed" data-toggle="collapse" data-target="#equipe_centro_custo">
                            <b> <i class="bi bi-person-check"></i> Equipe e centro de custo</b>
                        </div>
                    </div>
                    <div id="equipe_centro_custo" class="collapse">
                        <div class="card-body">
                            Em breve.
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <div class="card-title collapsed" data-toggle="collapse" data-target="#evidencias_entregas">
                            <b> <i class="bi bi-bookmark-check"></i> Evidências e Entregas</b>
                        </div>
                    </div>
                    <div id="evidencias_entregas" class="collapse">
                        <div class="card-body">
                            Em breve.
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <div class="card-title collapsed" data-toggle="collapse" data-target="#notas_pagamentos">
                            <b> <i class="bi bi-money"></i> Notas fiscais / recebimentos e pagamentos</b>
                        </div>
                    </div>
                    <div id="notas_pagamentos" class="collapse">
                        <div class="card-body">
                            Em breve.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>