# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 18 Oct 2022 14:00:52 +0000
*               @ALL          0
*               @user         8
