<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Tue, 18 Oct 2022 14:00:52 +0000
 */
$conf['title'] = 'Base de Conhecimento';
$conf['lang'] = 'pt-br';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
