# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 18 Oct 2022 14:00:52 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

root:$2y$10$f6vk7x0K9zgIZUwhU6OOGu4Zykuo4RsFCbZ13oQLHXgj62WUn2JDu:super user:werter@gmail.com:admin,user
