<?php
define('VERSAO', '1.1.0');

define('ADM_SISID', 74);

define('TIPO_DOCUMENTO_FLUXO_EXECUCAO_EDITAL', 17);
define('ESTADO_DOCUMENTO_SELECIONADO_PARA_SOLICITAR_SERVICO', 86);

define('TIPO_DOCUMENTO_FLUXO_ADERENCIA_CARTAO_BENEFICIOS', 7401);

define('ESTADO_DOCUMENTO_ADERENCIA_CARTAO_BENEFICIOS_AGUARDANDO_PAGAMENTO', 740101);
define('ESTADO_DOCUMENTO_ADERENCIA_CARTAO_BENEFICIOS_ATIVO', 740101);
define('ESTADO_DOCUMENTO_ADERENCIA_CARTAO_BENEFICIOS_CANCELADO', 740101);
define('ESTADO_DOCUMENTO_ADERENCIA_CARTAO_BENEFICIOS_INATIVO_FALTA_PAGAMENTO', 740101);



